name: CI/CD Pipeline for Flask App

on:
  push:
    branches:
      - Master
  pull_request:
    branches:
      - Master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Podman
      uses: redhat-actions/podman-login@v1

    - name: Log in to docker Container Registry
      uses: redhat-actions/podman-login@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        registry: docker.io

    - name: Build and tag the image
      id: build-image
      run: |
        IMAGE_ID=${{ secrets.DOCKER_HUB_USERNAME }}/flask-app
        VERSION=$(echo ${{ github.sha }} | cut -c1-8)
        podman build -t $IMAGE_ID:$VERSION .
        podman tag $IMAGE_ID:$VERSION $IMAGE_ID:latest
        echo "IMAGE_ID=$IMAGE_ID" >> $GITHUB_ENV
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Push the image
      run: |
        podman push ${{ env.IMAGE_ID }}:${{ env.VERSION }}
        podman push ${{ env.IMAGE_ID }}:latest
